// Comprehensive product list - Indian and Global consumer products
export const PRODUCTS = [
  // Indian Staple Foods & Grains
  "Basmati Rice",
  "Sona Masoori Rice",
  "Kolam Rice",
  "Brown Rice",
  "Wheat Flour (Atta)",
  "Maida (Refined Flour)",
  "Rava (Semolina)",
  "Besan (Gram Flour)",
  "Ragi Flour (Finger Millet)",
  "Jowar Flour (Sorghum)",
  "Bajra Flour (Pearl Millet)",
  "Rice Flour",
  "Cornflour",
  "Poha (Flattened Rice)",
  "Murmura (Puffed Rice)",
  "Upma Mix",
  
  // Indian Pulses & Legumes
  "Toor Dal (Pigeon Pea)",
  "Moong Dal (Green Gram)",
  "Chana Dal (Split Chickpea)",
  "Urad Dal (Black Gram)",
  "Masoor Dal (Red Lentil)",
  "Rajma (Kidney Beans)",
  "Kabuli Chana (Chickpeas)",
  "Black Chickpeas",
  "Mung Beans",
  "Soybean",
  
  // Indian Spices
  "Turmeric Powder",
  "Red Chili Powder",
  "Coriander Powder",
  "Cumin Powder",
  "Garam Masala",
  "Curry Powder",
  "Mustard Seeds",
  "Fenugreek Seeds",
  "Asafoetida (Hing)",
  "Cardamom",
  "Cinnamon",
  "Cloves",
  "Black Pepper",
  "Bay Leaves",
  "Fennel Seeds",
  "Carom Seeds (Ajwain)",
  "Nigella Seeds (Kalonji)",
  "Star Anise",
  "Dry Mango Powder (Amchur)",
  "Kasuri Methi (Dried Fenugreek Leaves)",
  
  // Indian Oils & Ghee
  "Mustard Oil",
  "Coconut Oil",
  "Groundnut Oil",
  "Sesame Oil",
  "Sunflower Oil",
  "Rice Bran Oil",
  "Ghee (Clarified Butter)",
  "Vanaspati (Hydrogenated Oil)",
  
  // Indian Snacks & Packaged Foods
  "Namkeen",
  "Bhujia",
  "Chakli",
  "Mathri",
  "Papad",
  "Biscuits (Parle-G)",
  "Marie Biscuits",
  "Cream Biscuits",
  "Rusk",
  "Instant Noodles (Maggi)",
  "Khakhra",
  "Chivda",
  "Farsan",
  "Samosa",
  
  // Indian Beverages
  "Masala Chai",
  "Assam Tea",
  "Darjeeling Tea",
  "Filter Coffee",
  "Instant Coffee",
  "Bournvita",
  "Horlicks",
  "Complan",
  "Rooh Afza",
  "Rasna",
  "Tang",
  "Frooti (Mango Drink)",
  "Limca",
  "Thums Up",
  "Buttermilk (Chaas)",
  "Lassi Mix",
  
  // Indian Dairy Products
  "Milk (Packaged)",
  "Paneer",
  "Curd (Dahi)",
  "Yogurt",
  "Butter",
  "Cheese Slices",
  "Condensed Milk",
  "Milk Powder",
  "Khoya (Mawa)",
  
  // Indian Sweets & Desserts
  "Jaggery (Gur)",
  "Sugar",
  "Honey",
  "Mishri (Rock Sugar)",
  "Gulab Jamun Mix",
  "Rasgulla",
  "Barfi",
  "Ladoo",
  "Halwa Mix",
  
  // Indian Pickles & Condiments
  "Mango Pickle",
  "Lime Pickle",
  "Mixed Vegetable Pickle",
  "Tamarind Chutney",
  "Mint Chutney",
  "Tomato Ketchup",
  "Green Chili Sauce",
  "Soy Sauce",
  "Vinegar",
  "Chili Sauce",
  
  // Indian Personal Care Products
  "Neem Soap",
  "Turmeric Soap",
  "Sandalwood Soap",
  "Medimix Soap",
  "Lifebuoy Soap",
  "Lux Soap",
  "Dove Soap",
  "Pears Soap",
  "Mysore Sandal Soap",
  "Coconut Hair Oil",
  "Amla Hair Oil",
  "Parachute Coconut Oil",
  "Dabur Amla Oil",
  "Navaratna Oil",
  "Vicco Turmeric Cream",
  "Boroline Cream",
  "Fair & Lovely Cream",
  "Ponds Cream",
  "Himalaya Face Wash",
  "Patanjali Aloe Vera Gel",
  "Colgate Toothpaste",
  "Pepsodent Toothpaste",
  "Dabur Red Toothpaste",
  "Meswak Toothpaste",
  
  // Global Grains & Cereals
  "Oats",
  "Quinoa",
  "Barley",
  "Couscous",
  "Bulgur Wheat",
  "Cornflakes",
  "Muesli",
  "Granola",
  "All-Purpose Flour",
  "Bread",
  "Pasta",
  "Noodles",
  "Spaghetti",
  "Macaroni",
  
  // Global Proteins
  "Chicken Breast",
  "Ground Beef",
  "Pork Chops",
  "Salmon",
  "Tuna (Canned)",
  "Eggs",
  "Tofu",
  "Tempeh",
  "Protein Powder",
  "Whey Protein",
  
  // Global Vegetables (Processed/Packaged)
  "Frozen Peas",
  "Frozen Corn",
  "Frozen Mixed Vegetables",
  "Canned Tomatoes",
  "Tomato Paste",
  "Tomato Sauce",
  "Baked Beans",
  "Canned Mushrooms",
  
  // Global Fruits (Processed)
  "Apple Juice",
  "Orange Juice",
  "Grape Juice",
  "Cranberry Juice",
  "Mixed Fruit Jam",
  "Strawberry Jam",
  "Peanut Butter",
  "Almond Butter",
  "Nutella",
  
  // Global Cooking Ingredients
  "Olive Oil",
  "Canola Oil",
  "Vegetable Oil",
  "Butter (Salted)",
  "Butter (Unsalted)",
  "Margarine",
  "Mayonnaise",
  "Salad Dressing",
  "Balsamic Vinegar",
  "Apple Cider Vinegar",
  "White Vinegar",
  "Salt",
  "Black Pepper",
  "Oregano",
  "Basil",
  "Thyme",
  "Rosemary",
  "Paprika",
  "Garlic Powder",
  "Onion Powder",
  "Baking Powder",
  "Baking Soda",
  "Yeast",
  "Vanilla Extract",
  "Cocoa Powder",
  "Chocolate Chips",
  
  // Global Beverages
  "Coffee",
  "Green Tea",
  "Black Tea",
  "Herbal Tea",
  "Chamomile Tea",
  "Earl Grey Tea",
  "Coca-Cola",
  "Pepsi",
  "Sprite",
  "Fanta",
  "Mountain Dew",
  "Red Bull",
  "Monster Energy Drink",
  "Gatorade",
  "Coconut Water",
  "Bottled Water",
  "Sparkling Water",
  "Apple Cider",
  "Hot Chocolate Mix",
  
  // Global Dairy Products
  "Whole Milk",
  "Skim Milk",
  "Almond Milk",
  "Soy Milk",
  "Oat Milk",
  "Cream Cheese",
  "Cheddar Cheese",
  "Mozzarella Cheese",
  "Parmesan Cheese",
  "Greek Yogurt",
  "Sour Cream",
  "Whipped Cream",
  "Ice Cream",
  
  // Global Snacks & Packaged Foods
  "Potato Chips",
  "Tortilla Chips",
  "Pretzels",
  "Popcorn",
  "Crackers",
  "Cookies",
  "Brownies",
  "Cake Mix",
  "Pancake Mix",
  "Cereal Bars",
  "Granola Bars",
  "Trail Mix",
  "Raisins",
  "Dried Cranberries",
  "Beef Jerky",
  "Rice Cakes",
  "Corn Chips",
  
  // Global Frozen Foods
  "Frozen Pizza",
  "Frozen French Fries",
  "Frozen Chicken Nuggets",
  "Ice Cream Bars",
  "Frozen Waffles",
  "Frozen Burrito",
  
  // Global Condiments & Sauces
  "Ketchup",
  "Mustard",
  "Hot Sauce",
  "BBQ Sauce",
  "Worcestershire Sauce",
  "Teriyaki Sauce",
  "Ranch Dressing",
  "Honey Mustard",
  "Sweet and Sour Sauce",
  "Sriracha",
  "Salsa",
  "Guacamole",
  "Hummus",
  
  // Baby Products
  "Baby Formula",
  "Baby Food (Cerelac)",
  "Baby Powder",
  "Baby Lotion",
  "Baby Shampoo",
  "Baby Oil",
  "Diaper Rash Cream",
  "Teething Gel",
  
  // Personal Care (Global)
  "Shampoo",
  "Conditioner",
  "Body Wash",
  "Hand Soap",
  "Face Wash",
  "Facial Cleanser",
  "Moisturizer",
  "Sunscreen",
  "Lotion",
  "Body Lotion",
  "Hand Cream",
  "Lip Balm",
  "Petroleum Jelly",
  "Deodorant",
  "Antiperspirant",
  "Perfume",
  "Cologne",
  "Aftershave",
  "Shaving Cream",
  "Hair Gel",
  "Hair Spray",
  "Hair Dye",
  "Nail Polish",
  "Nail Polish Remover",
  
  // Oral Care
  "Toothpaste",
  "Mouthwash",
  "Dental Floss",
  "Whitening Strips",
  "Denture Cleaner",
  
  // Household Cleaning Products
  "Dish Soap",
  "Dishwasher Detergent",
  "Laundry Detergent",
  "Fabric Softener",
  "Bleach",
  "All-Purpose Cleaner",
  "Glass Cleaner",
  "Floor Cleaner",
  "Toilet Cleaner",
  "Bathroom Cleaner",
  "Disinfectant Spray",
  "Hand Sanitizer",
  "Antibacterial Wipes",
  
  // Medicine & Health (OTC)
  "Paracetamol",
  "Ibuprofen",
  "Aspirin",
  "Cough Syrup",
  "Antacid",
  "Vitamin C Tablets",
  "Multivitamin",
  "Calcium Supplements",
  "Iron Supplements",
  "Omega-3 Supplements",
  "Probiotic Capsules",
  "First Aid Cream",
  "Antiseptic Cream",
  "Band-Aid",
  
  // Miscellaneous Common Products
  "Mosquito Repellent",
  "Mosquito Coil",
  "Incense Sticks (Agarbatti)",
  "Camphor",
  "Matches",
  "Candles",
  "Air Freshener",
  "Shoe Polish",
  "Ink",
  "Glue",
  "Correction Fluid",
  "Pencil Lead",
  "Eraser",
  "Crayons",
  "Markers",
  "Paint",
  "Varnish",
  "Sandpaper",
  "WD-40",
  "Super Glue",
  
  // Asian Products (Non-Indian)
  "Soy Milk",
  "Rice Vinegar",
  "Miso Paste",
  "Kimchi",
  "Nori (Seaweed Sheets)",
  "Wasabi",
  "Fish Sauce",
  "Oyster Sauce",
  "Hoisin Sauce",
  "Rice Wine",
  "Sesame Seeds",
  "Chia Seeds",
  "Flax Seeds",
  
  // European Products
  "Feta Cheese",
  "Brie Cheese",
  "Gouda Cheese",
  "Swiss Cheese",
  "Croissant",
  "Baguette",
  "Focaccia",
  "Pesto Sauce",
  "Marinara Sauce",
  "Alfredo Sauce",
  
  // Latin American Products
  "Tortillas",
  "Refried Beans",
  "Black Beans",
  "Pinto Beans",
  "Jalapeños",
  "Chipotle Sauce",
  "Enchilada Sauce",
  "Taco Seasoning",
  "Chorizo",
  
  // Middle Eastern Products
  "Tahini",
  "Pita Bread",
  "Falafel Mix",
  "Za'atar",
  "Sumac",
  "Pomegranate Molasses",
  "Halva",
  "Turkish Delight",
  
  // Beverages - Traditional & Specialty
  "Matcha Powder",
  "Bubble Tea Mix",
  "Masala Milk Mix",
  "Badam Milk Mix",
  "Saffron",
  "Rose Water",
  "Kewra Water",
  "Kokum",
  "Tamarind Concentrate"
];

// Export count for reference
export const PRODUCT_COUNT = PRODUCTS.length;

